name: saude-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - tqdm=4.66.4
  - faiss-cpu=1.7.4
  - pip
  - pip:
      - sentence-transformers==2.6.1
      - langchain
      - langchain-community
      - fastapi
      - uvicorn
      - transformers
      - torch
